# Prometheus Helm Chart Values
server:
  persistentVolume:
    enabled: true
    size: 10Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

alertmanager:
  enabled: true
  persistentVolume:
    enabled: true
    size: 5Gi

pushgateway:
  enabled: true

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

grafana:
  enabled: false  # 별도로 설치할 예정 