# Rocket.Chat Helm Chart Values
mongodb:
  enabled: false

externalMongoDB:
  mongoURL: "mongodb://rocketchat:rocketchat123@10.0.3.234:27017/rocketchat?replicaSet=rs0"

redis:
  enabled: false

externalRedis:
  redisURL: "redis://:rocketchat123@10.0.3.51:6379"

service:
  type: NodePort
  port: 3000

ingress:
  enabled: false

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80 