# Rocket.Chat Helm Chart Values
mongodb:
  enabled: false

externalMongoDB:
  mongoURL: "${mongodb_url}"

redis:
  enabled: false

externalRedis:
  redisURL: "${redis_url}"

service:
  type: NodePort
  port: 3000

ingress:
  enabled: false

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80 